language: java
jdk: openjdk8
before_install:
  - mkdir .bin
  - curl -Lo .bin/sbt https://raw.githubusercontent.com/coursier/sbt-extras/150686c3d67c9e531a381283a803eb53d72735ab/sbt
  - chmod +x .bin/sbt
  - export PATH="$(pwd)/.bin:$PATH"
  - export TRAVIS_SCALA_VERSION=2.12.10
script: ./.travis.sh
sudo: required
cache:
  directories:
  - $HOME/.cache
  - $HOME/.sbt
  - $HOME/standalone-stuff
  - $HOME/yarn-stuff
git:
  depth: false
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  - env: MASTER=local-distrib
  - env: MASTER=local
  - env: MASTER=standalone STANDALONE_CACHE=$HOME/standalone-stuff
  - env: MASTER=yarn-distrib YARN_CACHE=$HOME/yarn-stuff STANDALONE_CACHE=$HOME/yarn-cache
  - env: MASTER=yarn YARN_CACHE=$HOME/yarn-stuff
  - stage: release
    script: sbt ci-release
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
