language: scala
scala: 2.11.12
jdk: oraclejdk8
script: ./.travis.sh
sudo: required
cache:
  directories:
  - $HOME/.cache
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/standalone-stuff
  - $HOME/yarn-stuff
branches:
  only:
  - develop
matrix:
  include:
  - env: MASTER=local
  - env: MASTER=standalone STANDALONE_CACHE=$HOME/standalone-stuff
  - env: MASTER=yarn YARN_CACHE=$HOME/yarn-stuff
