language: scala
jdk: oraclejdk8
script: ./.travis.sh
sudo: required
cache:
  directories:
  - $HOME/.cache
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/standalone-stuff
  - $HOME/yarn-stuff
before_install:
  - git fetch --tags
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  - env: MASTER=local-distrib
    scala: 2.11.12
  - env: MASTER=local
    scala: 2.11.12
  - env: MASTER=local
    scala: 2.12.8
  - env: MASTER=standalone STANDALONE_CACHE=$HOME/standalone-stuff
    scala: 2.11.12
  - env: MASTER=yarn-distrib YARN_CACHE=$HOME/yarn-stuff STANDALONE_CACHE=$HOME/yarn-cache
    scala: 2.11.12
  - env: MASTER=yarn YARN_CACHE=$HOME/yarn-stuff
    scala: 2.11.12
  - env: MASTER=yarn YARN_CACHE=$HOME/yarn-stuff
    scala: 2.12.8
  - stage: release
    script: sbt ci-release
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
