name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        MASTER: ["local", "standalone", "yarn", "local-distrib", "yarn-distrib"]
    steps:
    - name: Don't convert LF to CRLF during checkout
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v8
      with:
        extraFiles: "[\".github/scripts/*\", \".github/workflows/ci.yml\", \"*.sh\"]"
        extraKey: test-${{ matrix.MASTER }}
    - run: .github/scripts/test.sh
      shell: bash
      env:
        MASTER: ${{ matrix.MASTER }}

  checks:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: true
    - name: Empty sources, orphan sources, missing test classes checks
      run: ./mill -i --import io.github.alexarchambault.mill::mill-checks:0.1.2 io.github.alexarchambault.millchecks.MillChecks/allChecks
      env:
        MILL_CHECKS_ORPHAN_SOURCES_IGNORE: >-
          mill-build
    - name: Ensure computing non-final sources doesn't trigger compilation
      run: ./mill --import io.github.alexarchambault.mill::mill-checks:0.1.2 io.github.alexarchambault.millchecks.MillChecks/bspChecks

  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/setup-action@v3
    - run: cs launch scalafmt -- --check
