name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        MASTER: ["local", "standalone", "yarn", "local-distrib", "yarn-distrib"]
    steps:
    - uses: actions/checkout@v7
    - uses: coursier/cache-action@v8
      with:
        disableFallback: true
    - run: .github/scripts/test.sh
      env:
        MASTER: ${{ matrix.MASTER }}

  checks:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Empty sources, orphan sources, missing test classes checks
      run: ./mill -i --import io.github.alexarchambault.mill::mill-checks:0.1.2 io.github.alexarchambault.millchecks.MillChecks/allChecks
      env:
        MILL_CHECKS_ORPHAN_SOURCES_IGNORE: >-
          mill-build
    - name: Ensure computing non-final sources doesn't trigger compilation
      run: ./mill --import io.github.alexarchambault.mill::mill-checks:0.1.2 io.github.alexarchambault.millchecks.MillChecks/bspChecks
    - name: Binary compatibility checks
      run: ./mill __.mimaReportBinaryIssues

  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: coursier/setup-action@v3
    - run: cs launch scalafmt -- --check

  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v8
      with:
        disableFallback: true
    - uses: coursier/setup-action@v3
      with:
        jvm: 21
    - name: Release
      run: ./mill -i mill.scalalib.SonatypeCentralPublishModule/
      env:
        MILL_PGP_SECRET_BASE64: ${{ secrets.PUBLISH_SECRET_KEY }}
        MILL_PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
        MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
